export type MapWorkbenchTargetHome =
  | "overview"
  | "data"
  | "layers"
  | "analyze"
  | "style"
  | "scene"
  | "publish"
  | "qa"
  | "review"
  | "diagnostics"
  | "extensions"
  | "status-bar"
  | "command-palette"
  | "canvas-overlay";

export type MapSurfaceInventoryKind =
  | "activity-rail-item"
  | "canvas-overlay"
  | "command-palette"
  | "dialog"
  | "drawer"
  | "file-input"
  | "hidden-toggle"
  | "inspector-context"
  | "panel-flag"
  | "processing-palette-command"
  | "quick-action"
  | "status-bar"
  | "toolbar-command"
  | "workspace-view";

export type MapSurfaceTargetSlot =
  | "bottom-panel"
  | "canvas"
  | "command-center"
  | "dialog"
  | "left-sidebar"
  | "right-inspector"
  | "status-bar"
  | "toolbar";

export interface MapSurfaceInventoryEntry {
  id: string;
  sourceId: string;
  label: string;
  kind: MapSurfaceInventoryKind;
  targetHome: MapWorkbenchTargetHome;
  targetSlot: MapSurfaceTargetSlot;
  currentSurface: string;
  targetSurface: string;
}

export const MAP_WORKBENCH_TARGET_HOMES = [
  "overview",
  "data",
  "layers",
  "analyze",
  "style",
  "scene",
  "publish",
  "qa",
  "review",
  "diagnostics",
  "extensions",
  "status-bar",
  "command-palette",
  "canvas-overlay",
] as const satisfies readonly MapWorkbenchTargetHome[];

export const MAP_SURFACE_INVENTORY = [
  {
    id: "toolbar.layers",
    sourceId: "layers",
    label: "Layer stack command",
    kind: "toolbar-command",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Layers activity > Stack",
  },
  {
    id: "toolbar.navigator",
    sourceId: "navigator",
    label: "Navigator cockpit command",
    kind: "toolbar-command",
    targetHome: "overview",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Overview activity > Readiness cockpit",
  },
  {
    id: "toolbar.task-lens-analyst",
    sourceId: "task-lens-analyst",
    label: "Analyst task lens command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Task lenses",
  },
  {
    id: "toolbar.task-lens-planner",
    sourceId: "task-lens-planner",
    label: "Planner task lens command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Task lenses",
  },
  {
    id: "toolbar.task-lens-reviewer",
    sourceId: "task-lens-reviewer",
    label: "Reviewer task lens command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Task lenses",
  },
  {
    id: "toolbar.task-lens-publisher",
    sourceId: "task-lens-publisher",
    label: "Publisher task lens command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Task lenses",
  },
  {
    id: "toolbar.import",
    sourceId: "import",
    label: "Local import command",
    kind: "toolbar-command",
    targetHome: "data",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Data activity > Import",
  },
  {
    id: "toolbar.services",
    sourceId: "services",
    label: "External services command",
    kind: "toolbar-command",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapToolbar",
    targetSurface: "Data activity > Connections",
  },
  {
    id: "toolbar.catalog",
    sourceId: "catalog",
    label: "Source catalog command",
    kind: "toolbar-command",
    targetHome: "data",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Data activity > Catalog",
  },
  {
    id: "toolbar.contents",
    sourceId: "contents",
    label: "Contents tree command",
    kind: "toolbar-command",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Layers activity > Contents",
  },
  {
    id: "toolbar.qa",
    sourceId: "qa",
    label: "Scientific QA command",
    kind: "toolbar-command",
    targetHome: "qa",
    targetSlot: "bottom-panel",
    currentSurface: "MapToolbar",
    targetSurface: "QA activity > Problems",
  },
  {
    id: "toolbar.query",
    sourceId: "query",
    label: "Natural-language query command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Query",
  },
  {
    id: "toolbar.workflow",
    sourceId: "workflow",
    label: "Spatial workflow command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "right-inspector",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Workflows",
  },
  {
    id: "toolbar.review-timeline",
    sourceId: "review-timeline",
    label: "Review timeline command",
    kind: "toolbar-command",
    targetHome: "review",
    targetSlot: "bottom-panel",
    currentSurface: "MapToolbar",
    targetSurface: "Review activity > Timeline",
  },
  {
    id: "toolbar.undo-map-action",
    sourceId: "undo-map-action",
    label: "Undo map action command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > History",
  },
  {
    id: "toolbar.redo-map-action",
    sourceId: "redo-map-action",
    label: "Redo map action command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > History",
  },
  {
    id: "toolbar.reset-layout",
    sourceId: "reset-layout",
    label: "Reset layout command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Layout recovery",
  },
  {
    id: "toolbar.collapse-panels",
    sourceId: "collapse-panels",
    label: "Collapse all panels command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Layout recovery",
  },
  {
    id: "toolbar.focus-map-canvas",
    sourceId: "focus-map-canvas",
    label: "Focus map canvas command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas > Keyboard focus",
  },
  {
    id: "toolbar.restore-default-widths",
    sourceId: "restore-default-widths",
    label: "Restore default widths command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Layout recovery",
  },
  {
    id: "toolbar.switch-density",
    sourceId: "switch-density",
    label: "Switch density command",
    kind: "toolbar-command",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Density",
  },
  {
    id: "toolbar.performance-diagnostics",
    sourceId: "performance-diagnostics",
    label: "Performance diagnostics command",
    kind: "toolbar-command",
    targetHome: "diagnostics",
    targetSlot: "bottom-panel",
    currentSurface: "MapToolbar",
    targetSurface: "Diagnostics activity > Render budget",
  },
  {
    id: "toolbar.plugin-registry",
    sourceId: "plugin-registry",
    label: "Plugin registry command",
    kind: "toolbar-command",
    targetHome: "extensions",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Extensions activity > Registry",
  },
  {
    id: "toolbar.processing-toolbox",
    sourceId: "processing-toolbox",
    label: "Processing toolbox command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Tools",
  },
  {
    id: "toolbar.model-builder",
    sourceId: "model-builder",
    label: "Model builder command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Models",
  },
  {
    id: "toolbar.figure-composer",
    sourceId: "figure-composer",
    label: "Figure composer command",
    kind: "toolbar-command",
    targetHome: "publish",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Publish activity > Figure",
  },
  {
    id: "toolbar.theme",
    sourceId: "theme",
    label: "Thematic styling command",
    kind: "toolbar-command",
    targetHome: "style",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Style activity > Renderer",
  },
  {
    id: "toolbar.extent",
    sourceId: "extent",
    label: "Restrict to extent command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "status-bar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > AOI and extent scope",
  },
  {
    id: "toolbar.lisa",
    sourceId: "lisa",
    label: "LISA statistics command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Spatial statistics",
  },
  {
    id: "toolbar.hotspot",
    sourceId: "hotspot",
    label: "Getis-Ord Gi* command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Spatial statistics",
  },
  {
    id: "toolbar.emerging-hotspot",
    sourceId: "emerging-hotspot",
    label: "Emerging hot spot command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Spatial statistics",
  },
  {
    id: "toolbar.sync",
    sourceId: "sync",
    label: "2D and 3D sync command",
    kind: "toolbar-command",
    targetHome: "scene",
    targetSlot: "status-bar",
    currentSurface: "MapToolbar",
    targetSurface: "Scene activity > Viewport sync",
  },
  {
    id: "toolbar.voxcity",
    sourceId: "voxcity",
    label: "VoxCity overlay command",
    kind: "toolbar-command",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Scene activity > VoxCity",
  },
  {
    id: "toolbar.pin-mode",
    sourceId: "pin-mode",
    label: "Pin placement command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Pins",
  },
  {
    id: "toolbar.pins",
    sourceId: "pins",
    label: "Pins sidebar command",
    kind: "toolbar-command",
    targetHome: "overview",
    targetSlot: "left-sidebar",
    currentSurface: "MapToolbar",
    targetSurface: "Overview activity > Notes",
  },
  {
    id: "toolbar.draw-point",
    sourceId: "draw-point",
    label: "Draw point command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Draw",
  },
  {
    id: "toolbar.draw-linestring",
    sourceId: "draw-linestring",
    label: "Draw line command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Draw",
  },
  {
    id: "toolbar.draw-polygon",
    sourceId: "draw-polygon",
    label: "Draw polygon command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Draw AOI",
  },
  {
    id: "toolbar.draw-rectangle",
    sourceId: "draw-rectangle",
    label: "Draw rectangle command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Draw AOI",
  },
  {
    id: "toolbar.draw-circle",
    sourceId: "draw-circle",
    label: "Draw circle command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Draw",
  },
  {
    id: "toolbar.drawings",
    sourceId: "drawings",
    label: "Drawings panel command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Drawings",
  },
  {
    id: "toolbar.annotations",
    sourceId: "annotations",
    label: "Annotation mode command",
    kind: "toolbar-command",
    targetHome: "publish",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Publish activity > Annotations",
  },
  {
    id: "toolbar.measure-distance",
    sourceId: "measure-distance",
    label: "Distance measurement command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Measure",
  },
  {
    id: "toolbar.measure-area",
    sourceId: "measure-area",
    label: "Area measurement command",
    kind: "toolbar-command",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapToolbar",
    targetSurface: "Canvas tool strip > Measure",
  },
  {
    id: "toolbar.measure-results",
    sourceId: "measure-results",
    label: "Measurement results command",
    kind: "toolbar-command",
    targetHome: "analyze",
    targetSlot: "bottom-panel",
    currentSurface: "MapToolbar",
    targetSurface: "Analyze activity > Measurements",
  },
  {
    id: "toolbar.save-project",
    sourceId: "save-project",
    label: "Save project command",
    kind: "toolbar-command",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapToolbar",
    targetSurface: "Status bar > Save state",
  },
  {
    id: "toolbar.load-project",
    sourceId: "load-project",
    label: "Load project command",
    kind: "toolbar-command",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapToolbar",
    targetSurface: "Status bar > Save state",
  },
  {
    id: "toolbar.export-image",
    sourceId: "export-image",
    label: "Image export command",
    kind: "toolbar-command",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapToolbar",
    targetSurface: "Publish activity > Figure",
  },
  {
    id: "toolbar.export-offline-package",
    sourceId: "export-offline-package",
    label: "Offline package command",
    kind: "toolbar-command",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapToolbar",
    targetSurface: "Publish activity > Offline Package",
  },
  {
    id: "toolbar.add-map-to-report",
    sourceId: "add-map-to-report",
    label: "Report handoff command",
    kind: "toolbar-command",
    targetHome: "publish",
    targetSlot: "right-inspector",
    currentSurface: "MapToolbar",
    targetSurface: "Publish activity > Report",
  },
  {
    id: "toolbar.export-geojson",
    sourceId: "export-geojson",
    label: "GeoJSON export command",
    kind: "toolbar-command",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapToolbar",
    targetSurface: "Publish activity > Data Export",
  },
  {
    id: "palette.command-palette",
    sourceId: "command-palette",
    label: "Command palette launcher",
    kind: "command-palette",
    targetHome: "command-palette",
    targetSlot: "command-center",
    currentSurface: "MapToolbar",
    targetSurface: "Command center > Palette",
  },
  {
    id: "palette.processing-dynamic",
    sourceId: "processing:*",
    label: "Processing tool palette command pattern",
    kind: "processing-palette-command",
    targetHome: "analyze",
    targetSlot: "command-center",
    currentSurface: "MapToolbar processing palette",
    targetSurface: "Analyze activity > Tools and command palette",
  },
  {
    id: "rail.overview.activity",
    sourceId: "overview",
    label: "Overview rail item",
    kind: "activity-rail-item",
    targetHome: "overview",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Overview activity",
  },
  {
    id: "rail.data.activity",
    sourceId: "data",
    label: "Data rail item",
    kind: "activity-rail-item",
    targetHome: "data",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Data activity",
  },
  {
    id: "rail.layers.activity",
    sourceId: "layers",
    label: "Layers rail item",
    kind: "activity-rail-item",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Layers activity",
  },
  {
    id: "rail.analyze.activity",
    sourceId: "analyze",
    label: "Analyze rail item",
    kind: "activity-rail-item",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Analyze activity",
  },
  {
    id: "rail.style.activity",
    sourceId: "style",
    label: "Style rail item",
    kind: "activity-rail-item",
    targetHome: "style",
    targetSlot: "right-inspector",
    currentSurface: "MapActivityRail",
    targetSurface: "Style activity",
  },
  {
    id: "rail.scene.activity",
    sourceId: "scene",
    label: "Scene rail item",
    kind: "activity-rail-item",
    targetHome: "scene",
    targetSlot: "right-inspector",
    currentSurface: "MapActivityRail",
    targetSurface: "Scene activity",
  },
  {
    id: "rail.publish.activity",
    sourceId: "publish",
    label: "Publish rail item",
    kind: "activity-rail-item",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapActivityRail",
    targetSurface: "Publish activity",
  },
  {
    id: "rail.review.activity",
    sourceId: "review",
    label: "Review rail item",
    kind: "activity-rail-item",
    targetHome: "review",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Review activity",
  },
  {
    id: "rail.diagnostics.activity",
    sourceId: "diagnostics",
    label: "Diagnostics rail item",
    kind: "activity-rail-item",
    targetHome: "diagnostics",
    targetSlot: "bottom-panel",
    currentSurface: "MapActivityRail",
    targetSurface: "Diagnostics activity",
  },
  {
    id: "rail.extensions.activity",
    sourceId: "extensions",
    label: "Extensions rail item",
    kind: "activity-rail-item",
    targetHome: "extensions",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Extensions activity",
  },
  {
    id: "rail.layers",
    sourceId: "layers",
    label: "Layer rail item",
    kind: "activity-rail-item",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Layers activity",
  },
  {
    id: "rail.catalog",
    sourceId: "catalog",
    label: "Catalog rail item",
    kind: "activity-rail-item",
    targetHome: "data",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Data activity",
  },
  {
    id: "rail.contents",
    sourceId: "contents",
    label: "Contents rail item",
    kind: "activity-rail-item",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Layers activity",
  },
  {
    id: "rail.processing",
    sourceId: "processing",
    label: "Processing rail item",
    kind: "activity-rail-item",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Analyze activity",
  },
  {
    id: "rail.layout",
    sourceId: "layout",
    label: "Layout rail item",
    kind: "activity-rail-item",
    targetHome: "publish",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Publish activity",
  },
  {
    id: "rail.scene3d",
    sourceId: "scene3d",
    label: "3D scene rail item",
    kind: "activity-rail-item",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "MapActivityRail",
    targetSurface: "Scene activity",
  },
  {
    id: "rail.qa",
    sourceId: "qa",
    label: "QA rail item",
    kind: "activity-rail-item",
    targetHome: "qa",
    targetSlot: "bottom-panel",
    currentSurface: "MapActivityRail",
    targetSurface: "QA activity",
  },
  {
    id: "rail.export",
    sourceId: "export",
    label: "Export rail item",
    kind: "activity-rail-item",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapActivityRail",
    targetSurface: "Publish activity",
  },
  {
    id: "rail.save",
    sourceId: "save",
    label: "Save rail item",
    kind: "activity-rail-item",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapActivityRail",
    targetSurface: "Status bar > Save state",
  },
  {
    id: "workspace.navigator",
    sourceId: "navigator",
    label: "Navigator workspace view",
    kind: "workspace-view",
    targetHome: "overview",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Overview activity",
  },
  {
    id: "workspace.explore",
    sourceId: "explore",
    label: "Explore workspace view",
    kind: "workspace-view",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Layers activity",
  },
  {
    id: "workspace.analyze",
    sourceId: "analyze",
    label: "Analyze workspace view",
    kind: "workspace-view",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Analyze activity",
  },
  {
    id: "quick-action.import-data",
    sourceId: "import-data",
    label: "Import data quick action",
    kind: "quick-action",
    targetHome: "data",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Data activity > Import",
  },
  {
    id: "quick-action.review-layers",
    sourceId: "review-layers",
    label: "Review layers quick action",
    kind: "quick-action",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Layers activity > Stack",
  },
  {
    id: "quick-action.open-pins",
    sourceId: "open-pins",
    label: "Pins and notes quick action",
    kind: "quick-action",
    targetHome: "overview",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Overview activity > Notes",
  },
  {
    id: "quick-action.draw-aoi",
    sourceId: "draw-aoi",
    label: "Draw AOI quick action",
    kind: "quick-action",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Canvas tool strip > Draw AOI",
  },
  {
    id: "quick-action.measure",
    sourceId: "measure",
    label: "Measure quick action",
    kind: "quick-action",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Canvas tool strip > Measure",
  },
  {
    id: "quick-action.theme-data",
    sourceId: "theme-data",
    label: "Theme data quick action",
    kind: "quick-action",
    targetHome: "style",
    targetSlot: "left-sidebar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Style activity > Renderer",
  },
  {
    id: "quick-action.export-map",
    sourceId: "export-map",
    label: "Export quick action",
    kind: "quick-action",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Publish activity > Export",
  },
  {
    id: "quick-action.save-project",
    sourceId: "save-project",
    label: "Save project quick action",
    kind: "quick-action",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapWorkspaceCockpit",
    targetSurface: "Status bar > Save state",
  },
  {
    id: "state.showSidebar",
    sourceId: "showSidebar",
    label: "Pin sidebar visibility",
    kind: "panel-flag",
    targetHome: "overview",
    targetSlot: "left-sidebar",
    currentSurface: "MapPinSidebar",
    targetSurface: "Overview activity > Notes",
  },
  {
    id: "state.showLayerPanel",
    sourceId: "showLayerPanel",
    label: "Layer panel visibility",
    kind: "panel-flag",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapLayerManager rail",
    targetSurface: "Layers activity > Stack",
  },
  {
    id: "state.showChoroplethPanel",
    sourceId: "showChoroplethPanel",
    label: "Choropleth panel visibility",
    kind: "panel-flag",
    targetHome: "style",
    targetSlot: "left-sidebar",
    currentSurface: "MapChoroplethLayer floating panel",
    targetSurface: "Style activity > Renderer",
  },
  {
    id: "state.showClusterViz",
    sourceId: "showClusterViz",
    label: "LISA cluster panel visibility",
    kind: "panel-flag",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapClusterViz floating panel",
    targetSurface: "Analyze activity > Spatial statistics",
  },
  {
    id: "state.showHotSpotViz",
    sourceId: "showHotSpotViz",
    label: "Getis-Ord hot spot panel visibility",
    kind: "panel-flag",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapHotSpotViz floating panel",
    targetSurface: "Analyze activity > Spatial statistics",
  },
  {
    id: "state.showEmergingHotSpotViz",
    sourceId: "showEmergingHotSpotViz",
    label: "Emerging hot spot panel visibility",
    kind: "panel-flag",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapEmergingHotSpotViz floating panel",
    targetSurface: "Analyze activity > Spatial statistics",
  },
  {
    id: "state.showVoxCityOverlay",
    sourceId: "showVoxCityOverlay",
    label: "VoxCity overlay visibility",
    kind: "panel-flag",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "MapVoxCityOverlay",
    targetSurface: "Scene activity > VoxCity",
  },
  {
    id: "state.showScientificQAPanel",
    sourceId: "showScientificQAPanel",
    label: "Scientific QA panel visibility",
    kind: "panel-flag",
    targetHome: "qa",
    targetSlot: "bottom-panel",
    currentSurface: "ScientificQAPanel",
    targetSurface: "QA activity > Problems",
  },
  {
    id: "state.showNLQueryPanel",
    sourceId: "showNLQueryPanel",
    label: "Natural-language query panel visibility",
    kind: "panel-flag",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapNLQueryPanel",
    targetSurface: "Analyze activity > Query",
  },
  {
    id: "state.showWorkflowDrawer",
    sourceId: "showWorkflowDrawer",
    label: "Spatial workflow drawer visibility",
    kind: "drawer",
    targetHome: "analyze",
    targetSlot: "right-inspector",
    currentSurface: "MapWorkflowDrawer",
    targetSurface: "Analyze activity > Workflows",
  },
  {
    id: "state.showReviewTimeline",
    sourceId: "showReviewTimeline",
    label: "Review timeline visibility",
    kind: "panel-flag",
    targetHome: "review",
    targetSlot: "bottom-panel",
    currentSurface: "MapReviewTimelinePanel",
    targetSurface: "Review activity > Timeline",
  },
  {
    id: "state.showFigureComposer",
    sourceId: "showFigureComposer",
    label: "Figure composer visibility",
    kind: "panel-flag",
    targetHome: "publish",
    targetSlot: "left-sidebar",
    currentSurface: "MapLayoutDesignerPanel",
    targetSurface: "Publish activity > Figure",
  },
  {
    id: "state.showRasterPanel",
    sourceId: "showRasterPanel",
    label: "Raster evidence panel visibility",
    kind: "panel-flag",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "RasterLayerPanel",
    targetSurface: "Scene activity > Raster",
  },
  {
    id: "state.show3DPanel",
    sourceId: "show3DPanel",
    label: "3D scene panel visibility",
    kind: "panel-flag",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "Scene3DPanel",
    targetSurface: "Scene activity > 3D",
  },
  {
    id: "state.showZoningPanel",
    sourceId: "showZoningPanel",
    label: "Zoning rules panel visibility",
    kind: "panel-flag",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "ZoningRulesPanel",
    targetSurface: "Scene activity > Zoning",
  },
  {
    id: "state.showMassingPanel",
    sourceId: "showMassingPanel",
    label: "Massing scenario panel visibility",
    kind: "panel-flag",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "MassingScenarioPanel",
    targetSurface: "Scene activity > Massing",
  },
  {
    id: "state.showSunShadowPanel",
    sourceId: "showSunShadowPanel",
    label: "Sun and shadow panel visibility",
    kind: "panel-flag",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "SunShadowPanel",
    targetSurface: "Scene activity > Sun/Shadow",
  },
  {
    id: "state.showInteractionStrip",
    sourceId: "showInteractionStrip",
    label: "3D interaction strip visibility",
    kind: "canvas-overlay",
    targetHome: "scene",
    targetSlot: "canvas",
    currentSurface: "Scene3DInteractionStrip",
    targetSurface: "Scene activity > 3D controls",
  },
  {
    id: "state.showComparisonStrip",
    sourceId: "showComparisonStrip",
    label: "Scenario comparison strip visibility",
    kind: "canvas-overlay",
    targetHome: "scene",
    targetSlot: "canvas",
    currentSurface: "ScenarioComparisonStrip",
    targetSurface: "Scene activity > Scenario comparison",
  },
  {
    id: "state.showPerformanceDiagnostics",
    sourceId: "showPerformanceDiagnostics",
    label: "Performance diagnostics visibility",
    kind: "panel-flag",
    targetHome: "diagnostics",
    targetSlot: "bottom-panel",
    currentSurface: "MapPerformanceDiagnosticsPanel",
    targetSurface: "Diagnostics activity > Render budget",
  },
  {
    id: "state.showProcessingToolbox",
    sourceId: "showProcessingToolbox",
    label: "Processing toolbox visibility",
    kind: "panel-flag",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapProcessingToolboxPanel",
    targetSurface: "Analyze activity > Tools",
  },
  {
    id: "state.showModelBuilder",
    sourceId: "showModelBuilder",
    label: "Model builder visibility",
    kind: "panel-flag",
    targetHome: "analyze",
    targetSlot: "left-sidebar",
    currentSurface: "MapModelBuilderPanel",
    targetSurface: "Analyze activity > Models",
  },
  {
    id: "state.showPluginPanel",
    sourceId: "showPluginPanel",
    label: "Plugin panel visibility",
    kind: "panel-flag",
    targetHome: "extensions",
    targetSlot: "left-sidebar",
    currentSurface: "MapPluginPanel",
    targetSurface: "Extensions activity > Registry",
  },
  {
    id: "state.showCatalog",
    sourceId: "showCatalog",
    label: "Catalog panel visibility",
    kind: "panel-flag",
    targetHome: "data",
    targetSlot: "left-sidebar",
    currentSurface: "MapCatalogPanel",
    targetSurface: "Data activity > Catalog",
  },
  {
    id: "state.showContents",
    sourceId: "showContents",
    label: "Contents panel visibility",
    kind: "panel-flag",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapContentsTreePanel",
    targetSurface: "Layers activity > Contents",
  },
  {
    id: "state.showExternalServiceDialog",
    sourceId: "showExternalServiceDialog",
    label: "External services dialog visibility",
    kind: "dialog",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapServiceDialog",
    targetSurface: "Data activity > Connections",
  },
  {
    id: "state.showDrawPanel",
    sourceId: "showDrawPanel",
    label: "Draw panel visibility",
    kind: "panel-flag",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapDrawingManager",
    targetSurface: "Canvas tool strip > Draw",
  },
  {
    id: "state.showMeasurePanel",
    sourceId: "showMeasurePanel",
    label: "Measurement panel visibility",
    kind: "panel-flag",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapMeasurementTool",
    targetSurface: "Canvas tool strip > Measure",
  },
  {
    id: "state.showImportProgress",
    sourceId: "showImportProgress",
    label: "Import progress HUD visibility",
    kind: "canvas-overlay",
    targetHome: "data",
    targetSlot: "canvas",
    currentSurface: "Map canvas import progress HUD",
    targetSurface: "Data activity > Import progress",
  },
  {
    id: "state.showImportHub",
    sourceId: "showImportHub",
    label: "Import hub dialog visibility",
    kind: "dialog",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapDataImportHubDialog",
    targetSurface: "Data activity > Import",
  },
  {
    id: "state.showExportDialog",
    sourceId: "showExportDialog",
    label: "Data export dialog visibility",
    kind: "dialog",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapDataExportDialog",
    targetSurface: "Publish activity > Data Export",
  },
  {
    id: "state.showMapExportDialog",
    sourceId: "showMapExportDialog",
    label: "Map image export dialog visibility",
    kind: "dialog",
    targetHome: "publish",
    targetSlot: "dialog",
    currentSurface: "MapExportDialog",
    targetSurface: "Publish activity > Figure",
  },
  {
    id: "state.inspectorLayerId",
    sourceId: "inspectorLayerId",
    label: "Layer inspector context",
    kind: "inspector-context",
    targetHome: "layers",
    targetSlot: "right-inspector",
    currentSurface: "LayerInspector",
    targetSurface: "Right inspector > Layer",
  },
  {
    id: "state.attributeTableLayerId",
    sourceId: "attributeTableLayerId",
    label: "Attribute table context",
    kind: "panel-flag",
    targetHome: "layers",
    targetSlot: "bottom-panel",
    currentSurface: "MapAttributeTable",
    targetSurface: "Bottom panel > Attributes",
  },
  {
    id: "state.pointSymbologyLayerId",
    sourceId: "pointSymbologyLayerId",
    label: "Point symbology context",
    kind: "panel-flag",
    targetHome: "style",
    targetSlot: "right-inspector",
    currentSurface: "Point symbology floating panel",
    targetSurface: "Style activity > Symbols",
  },
  {
    id: "state.activeUrbanMethodPreview",
    sourceId: "activeUrbanMethodPreview",
    label: "Urban method compatibility rail context",
    kind: "inspector-context",
    targetHome: "analyze",
    targetSlot: "right-inspector",
    currentSurface: "MapUrbanMethodCompatibilityRail",
    targetSurface: "Right inspector > Analysis run",
  },
  {
    id: "state.reportHandoffDraft",
    sourceId: "reportHandoffDraft",
    label: "Report handoff drawer context",
    kind: "drawer",
    targetHome: "publish",
    targetSlot: "right-inspector",
    currentSurface: "MapReportHandoffDrawer",
    targetSurface: "Publish activity > Report",
  },
  {
    id: "state.selectionStatsSummary",
    sourceId: "selectionStatsSummary",
    label: "Selection statistics HUD context",
    kind: "canvas-overlay",
    targetHome: "analyze",
    targetSlot: "canvas",
    currentSurface: "Selection statistics canvas HUD",
    targetSurface: "Analyze activity > Statistics",
  },
  {
    id: "state.isFlowDispatchDialogOpen",
    sourceId: "isFlowDispatchDialogOpen",
    label: "AOI workflow dispatch dialog visibility",
    kind: "dialog",
    targetHome: "analyze",
    targetSlot: "dialog",
    currentSurface: "Map analysis dispatch dialog",
    targetSurface: "Analyze activity > Workflow launch",
  },
  {
    id: "state.pendingImportPreview",
    sourceId: "pendingImportPreview",
    label: "Import preview dialog context",
    kind: "dialog",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapImportPreviewDialog",
    targetSurface: "Data activity > Import preflight",
  },
  {
    id: "state.pendingCsvImport",
    sourceId: "pendingCsvImport",
    label: "CSV import mapping dialog context",
    kind: "dialog",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapCsvImportDialog",
    targetSurface: "Data activity > CSV mapping",
  },
  {
    id: "state.pendingColumnarImport",
    sourceId: "pendingColumnarImport",
    label: "Columnar import dialog context",
    kind: "dialog",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapColumnarImportDialog",
    targetSurface: "Data activity > Columnar import",
  },
  {
    id: "state.isDragActive",
    sourceId: "isDragActive",
    label: "Drag import overlay state",
    kind: "canvas-overlay",
    targetHome: "data",
    targetSlot: "canvas",
    currentSurface: "Map canvas drop overlay",
    targetSurface: "Data activity > Import preflight",
  },
  {
    id: "state.dispatchFeedback",
    sourceId: "dispatchFeedback",
    label: "Map dispatch feedback HUD",
    kind: "canvas-overlay",
    targetHome: "analyze",
    targetSlot: "canvas",
    currentSurface: "Map dispatch feedback HUD",
    targetSurface: "Analyze activity > Workflow launch",
  },
  {
    id: "state.activeTemporalLayer",
    sourceId: "activeTemporalLayer",
    label: "Temporal playback overlay context",
    kind: "canvas-overlay",
    targetHome: "scene",
    targetSlot: "bottom-panel",
    currentSurface: "MapTemporalPlayer",
    targetSurface: "Scene activity > Temporal",
  },
  {
    id: "state.temporalStoreFrameCount",
    sourceId: "temporalStoreFrameCount",
    label: "Temporal player panel host context",
    kind: "canvas-overlay",
    targetHome: "scene",
    targetSlot: "bottom-panel",
    currentSurface: "TemporalPlayerPanel host",
    targetSurface: "Scene activity > Temporal",
  },
  {
    id: "file-input.local-import",
    sourceId: "hidden-local-file-input",
    label: "Hidden local import file input",
    kind: "file-input",
    targetHome: "data",
    targetSlot: "dialog",
    currentSurface: "MapExplorerModalComposition hidden input",
    targetSurface: "Data activity > Import",
  },
  {
    id: "hidden-toggle.raster",
    sourceId: "toggle-raster-panel",
    label: "Hidden raster panel toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > Raster",
  },
  {
    id: "hidden-toggle.scene3d",
    sourceId: "toggle-3d-panel",
    label: "Hidden 3D scene panel toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > 3D",
  },
  {
    id: "hidden-toggle.zoning",
    sourceId: "toggle-zoning-panel",
    label: "Hidden zoning panel toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > Zoning",
  },
  {
    id: "hidden-toggle.massing",
    sourceId: "toggle-massing-panel",
    label: "Hidden massing panel toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > Massing",
  },
  {
    id: "hidden-toggle.sunshadow",
    sourceId: "toggle-sunshadow-panel",
    label: "Hidden sun/shadow panel toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "left-sidebar",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > Sun/Shadow",
  },
  {
    id: "hidden-toggle.interaction-strip",
    sourceId: "toggle-3d-interaction-strip",
    label: "Hidden 3D interaction strip toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "canvas",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > 3D controls",
  },
  {
    id: "hidden-toggle.comparison-strip",
    sourceId: "toggle-3d-comparison-strip",
    label: "Hidden scenario comparison strip toggle",
    kind: "hidden-toggle",
    targetHome: "scene",
    targetSlot: "canvas",
    currentSurface: "Hidden test-only toggle",
    targetSurface: "Scene activity > Scenario comparison",
  },
  {
    id: "surface.MapLayerManager",
    sourceId: "MapLayerManager",
    label: "Layer manager component",
    kind: "panel-flag",
    targetHome: "layers",
    targetSlot: "left-sidebar",
    currentSurface: "MapLayerManager",
    targetSurface: "Layers activity > Stack",
  },
  {
    id: "surface.MapSelectionTools",
    sourceId: "MapSelectionTools",
    label: "Selection tools overlay",
    kind: "canvas-overlay",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapSelectionTools",
    targetSurface: "Canvas tool strip > Selection",
  },
  {
    id: "surface.MapCanvasControls",
    sourceId: "MapCanvasControls",
    label: "Canvas control standard",
    kind: "canvas-overlay",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapCanvasControls",
    targetSurface: "Canvas controls > Viewport, basemap, CRS, and publish furniture",
  },
  {
    id: "surface.MapLegendOverlay",
    sourceId: "MapLegendOverlay",
    label: "Map legend overlay",
    kind: "canvas-overlay",
    targetHome: "publish",
    targetSlot: "canvas",
    currentSurface: "MapLegendOverlay",
    targetSurface: "Publish activity > Legend",
  },
  {
    id: "surface.MapPerformanceBudgetBanner",
    sourceId: "MapPerformanceBudgetBanner",
    label: "Performance budget banner",
    kind: "canvas-overlay",
    targetHome: "diagnostics",
    targetSlot: "canvas",
    currentSurface: "MapPerformanceBudgetBanner",
    targetSurface: "Diagnostics activity > Render budget",
  },
  {
    id: "surface.WorkflowPreviewOverlay",
    sourceId: "WorkflowPreviewOverlay",
    label: "Workflow preview overlay",
    kind: "canvas-overlay",
    targetHome: "analyze",
    targetSlot: "canvas",
    currentSurface: "WorkflowPreviewOverlay",
    targetSurface: "Analyze activity > Workflow preview",
  },
  {
    id: "surface.MapContextMenu",
    sourceId: "MapContextMenu",
    label: "Map context menu",
    kind: "canvas-overlay",
    targetHome: "canvas-overlay",
    targetSlot: "canvas",
    currentSurface: "MapContextMenu",
    targetSurface: "Canvas overlay > Context actions",
  },
  {
    id: "surface.MapAnnotationLayer",
    sourceId: "MapAnnotationLayer",
    label: "Annotation layer overlay",
    kind: "canvas-overlay",
    targetHome: "publish",
    targetSlot: "canvas",
    currentSurface: "MapAnnotationLayer",
    targetSurface: "Publish activity > Annotations",
  },
  {
    id: "status.MapStatusBarWithCursor",
    sourceId: "MapStatusBarWithCursor",
    label: "Map status bar",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar",
  },
  {
    id: "status.project",
    sourceId: "projectId",
    label: "Project status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > Project",
  },
  {
    id: "status.workspace",
    sourceId: "workspaceLabel",
    label: "Workspace status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > Workspace",
  },
  {
    id: "status.crs",
    sourceId: "crs",
    label: "CRS status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > CRS shortcut",
  },
  {
    id: "status.sync",
    sourceId: "syncStatus",
    label: "Viewport sync status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > Sync",
  },
  {
    id: "status.selection",
    sourceId: "selectedFeatureCount",
    label: "Selection count status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > Selection",
  },
  {
    id: "status.qa",
    sourceId: "qaStatus",
    label: "QA status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > QA shortcut",
  },
  {
    id: "status.performance",
    sourceId: "performanceMode",
    label: "Render mode status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > Render mode",
  },
  {
    id: "status.persistence",
    sourceId: "autoSaveEnabled",
    label: "Persistence status",
    kind: "status-bar",
    targetHome: "status-bar",
    targetSlot: "status-bar",
    currentSurface: "MapStatusBarWithCursor",
    targetSurface: "Status bar > Save state",
  },
] as const satisfies readonly MapSurfaceInventoryEntry[];

export function getMapSurfaceInventoryByHome(
  targetHome: MapWorkbenchTargetHome,
): readonly MapSurfaceInventoryEntry[] {
  return MAP_SURFACE_INVENTORY.filter((entry) => entry.targetHome === targetHome);
}

export function getMapSurfaceInventoryEntry(sourceId: string): MapSurfaceInventoryEntry | undefined {
  return MAP_SURFACE_INVENTORY.find((entry) => entry.sourceId === sourceId);
}
