import type {
  DetectedObject,
  ObjectDetectionResult,
} from '@/engine/geoai/cv';
import type { ObjectDetectionRunMetadata } from '@/engine/geoai/hooks';
import type { CompletedAnalysisRun } from '@/features/urbanAnalytics/lib/types';
import {
  adaptDetectionResult,
  type AnalysisAdapterResult,
  createAnalysisCompletedRun,
  createAnalysisMapOutput,
} from '@/services/map/MapEngineAdapter';

export interface DetectionPublicationArgs {
  detection: ObjectDetectionResult;
  confidenceThreshold: number;
  selectedClasses: readonly string[];
  classColors: Record<string, string>;
  classLabels: Record<string, string>;
  runMetadata?: ObjectDetectionRunMetadata;
  runId?: string;
  label?: string;
  insertedAt?: string;
}

export interface DetectionClassSummaryRow {
  className: string;
  label: string;
  count: number;
}

export interface DetectionPublicationArtifacts {
  runId: string;
  label: string;
  adapted: AnalysisAdapterResult;
  completedRun: CompletedAnalysisRun;
  publishMessage: string;
  classCounts: DetectionClassSummaryRow[];
  detectionCount: number;
  narrative: string;
}

function emptyFeatureCollection(): GeoJSON.FeatureCollection {
  return { type: 'FeatureCollection', features: [] };
}

function asFeatureCollection(result: AnalysisAdapterResult): GeoJSON.FeatureCollection {
  const sourceData = result.layer.sourceData;
  if (sourceData && typeof sourceData === 'object' && (sourceData as GeoJSON.FeatureCollection).type === 'FeatureCollection') {
    return sourceData as GeoJSON.FeatureCollection;
  }
  return emptyFeatureCollection();
}

function getNumericProperty(properties: GeoJSON.GeoJsonProperties | null | undefined, key: string): number {
  const value = properties?.[key];
  return typeof value === 'number' && Number.isFinite(value) ? Number(value) : 0;
}

export function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'object-detection';
}

export function summarizeDetections(detections: readonly DetectedObject[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const detection of detections) {
    counts.set(detection.className, (counts.get(detection.className) ?? 0) + 1);
  }
  return counts;
}

export function buildDetectionNarrative(
  label: string,
  confidenceThreshold: number,
  selectedClasses: readonly string[],
  detections: readonly DetectedObject[],
  classLabels: Record<string, string>,
  runMetadata?: ObjectDetectionRunMetadata,
): string {
  const counts = Array.from(summarizeDetections(detections).entries())
    .sort((left, right) => right[1] - left[1])
    .map(([className, count]) => `${classLabels[className] ?? className}: ${count}`)
    .join(', ');

  const executionSummary = runMetadata
    ? runMetadata.executionMode === 'demo-mode'
      ? `Demo mode remained explicit for ${runMetadata.sourceTitle}; detections were generated by the synthetic fallback instead of a weight-backed model.`
      : `Real model ${runMetadata.modelId} ran on ${runMetadata.sourceTitle} via the ${runMetadata.backend.toUpperCase()} backend.`
    : null;

  return [
    `${label} completed at confidence ${confidenceThreshold.toFixed(2)} with ${selectedClasses.length} enabled class${selectedClasses.length === 1 ? '' : 'es'}.`,
    ...(executionSummary ? [executionSummary] : []),
    detections.length > 0
      ? `The run retained ${detections.length} detection${detections.length === 1 ? '' : 's'} after thresholding and non-maximum suppression. ${counts ? `Class distribution: ${counts}.` : ''}`
      : 'No detections met the active threshold in the current scene.',
    'The published result is traceable in Map Explorer and Completed Run Review for inspection, narrative drafting, and reporting.',
  ].join('\n');
}

export function buildDetectionPreviewRows(featureCollection: GeoJSON.FeatureCollection) {
  return featureCollection.features.slice(0, 8).map((feature, index) => {
    const properties = feature.properties ?? {};
    return {
      detection_id: typeof properties.detection_id === 'string' ? properties.detection_id : `detection-${index + 1}`,
      detection_class: typeof properties.detection_class === 'string' ? properties.detection_class : 'unknown',
      confidence: Number(getNumericProperty(properties, 'confidence').toFixed(3)),
      bbox_west: Number(getNumericProperty(properties, 'bbox_west').toFixed(6)),
      bbox_south: Number(getNumericProperty(properties, 'bbox_south').toFixed(6)),
      bbox_east: Number(getNumericProperty(properties, 'bbox_east').toFixed(6)),
      bbox_north: Number(getNumericProperty(properties, 'bbox_north').toFixed(6)),
    };
  });
}

function buildDetectionRunMetadataPreview(runMetadata: ObjectDetectionRunMetadata) {
  return {
    execution_mode: runMetadata.executionMode,
    demo_mode: runMetadata.executionMode === 'demo-mode',
    model_id: runMetadata.modelId,
    backend: runMetadata.backend,
    tile_size: runMetadata.tileSize,
    overlap: runMetadata.overlap,
    confidence_thresholds: JSON.stringify(runMetadata.confidenceThresholds),
    nms_iou_threshold: Number(runMetadata.nmsIouThreshold.toFixed(3)),
    source_id: runMetadata.sourceId,
    source_title: runMetadata.sourceTitle,
    source_kind: runMetadata.sourceKind,
    source_ref: runMetadata.sourceRef,
    source_runtime_mode: runMetadata.sourceRuntimeMode,
    elapsed_ms: runMetadata.elapsedMs,
    image_id: runMetadata.imageId,
  };
}

function summarizePublishedClasses(
  featureCollection: GeoJSON.FeatureCollection,
  classLabels: Record<string, string>,
): DetectionClassSummaryRow[] {
  const counts = new Map<string, number>();

  for (const feature of featureCollection.features) {
    const className = typeof feature.properties?.detection_class === 'string'
      ? feature.properties.detection_class
      : 'unknown';
    counts.set(className, (counts.get(className) ?? 0) + 1);
  }

  return Array.from(counts.entries())
    .map(([className, count]) => ({
      className,
      label: classLabels[className] ?? className,
      count,
    }))
    .sort((left, right) => right.count - left.count);
}

export function buildObjectDetectionPublication({
  detection,
  confidenceThreshold,
  selectedClasses,
  classColors,
  classLabels,
  runMetadata,
  runId = `object-detection-${Date.now()}`,
  label = `Object Detection — ${detection.imageId ?? 'urban-scene'}`,
  insertedAt,
}: DetectionPublicationArgs): DetectionPublicationArtifacts {
  const adapted = adaptDetectionResult({
    result: detection,
    runId,
    ...(insertedAt ? { runTimestamp: insertedAt } : {}),
    layerId: `${slugify(label)}-${runId}`,
    layerName: label,
    confidenceThreshold,
    classColors,
    parameters: {
      selectedClasses: [...selectedClasses],
      confidenceThreshold,
      imageId: detection.imageId,
      modelId: detection.modelId,
      ...(runMetadata
        ? {
            executionMode: runMetadata.executionMode,
            backend: runMetadata.backend,
            tileSize: runMetadata.tileSize,
            overlap: runMetadata.overlap,
            confidenceThresholds: runMetadata.confidenceThresholds,
            nmsIouThreshold: runMetadata.nmsIouThreshold,
            sourceId: runMetadata.sourceId,
            sourceTitle: runMetadata.sourceTitle,
            sourceKind: runMetadata.sourceKind,
            sourceRef: runMetadata.sourceRef,
            sourceRuntimeMode: runMetadata.sourceRuntimeMode,
            elapsedMs: runMetadata.elapsedMs,
          }
        : {}),
    },
  });

  const publishedCollection = asFeatureCollection(adapted);
  const detectionCount = publishedCollection.features.length;
  const classCounts = summarizePublishedClasses(publishedCollection, classLabels);
  const narrative = buildDetectionNarrative(
    label,
    confidenceThreshold,
    selectedClasses,
    detection.detections,
    classLabels,
    runMetadata,
  );

  const completedRun = createAnalysisCompletedRun(adapted, {
    flowId: 'object_detection',
    runId,
    ...(insertedAt ? { insertedAt } : {}),
    label,
    paragraph: narrative,
    paragraphPreview: narrative,
    paragraphFull: narrative,
    mapOutputs: [createAnalysisMapOutput(adapted)],
    chartOutputs: [
      {
        id: `${runId}-class-counts`,
        type: 'bar',
        title: `${label} Class Counts`,
        data: classCounts,
      },
    ],
    dataOutputs: [
      {
        id: `${runId}-detections`,
        format: 'object-detections',
        rows: detectionCount,
        columns: ['detection_id', 'detection_class', 'confidence', 'bbox_west', 'bbox_south', 'bbox_east', 'bbox_north'],
        preview: buildDetectionPreviewRows(publishedCollection),
      },
      ...(runMetadata
        ? [{
            id: `${runId}-run-metadata`,
            format: 'object-detection-run-metadata',
            rows: 1,
            columns: [
              'execution_mode',
              'demo_mode',
              'model_id',
              'backend',
              'tile_size',
              'overlap',
              'confidence_thresholds',
              'nms_iou_threshold',
              'source_id',
              'source_title',
              'source_kind',
              'source_ref',
              'source_runtime_mode',
              'elapsed_ms',
              'image_id',
            ],
            preview: [buildDetectionRunMetadataPreview(runMetadata)],
          }]
        : []),
    ],
  });

  return {
    runId,
    label,
    adapted,
    completedRun,
    classCounts,
    detectionCount,
    narrative,
    publishMessage: detectionCount > 0
      ? `Published ${detectionCount} detection${detectionCount === 1 ? '' : 's'} to Map Explorer and Completed Run Review.`
      : 'Detection completed with no retained objects at the active threshold. Map Explorer and Completed Run Review were updated with an empty result set for traceability.',
  };
}