// Heavy per-language template content map for NewFileModal (MFP-10).
// Split out so NewFileModal can lazy-import() it only when a file is created,
// keeping the eager chunk small (metadata stays in newFileTemplates.ts).

export const getTemplateContentByLanguage = (
  languageId: string,
  templateId: string,
  fileName: string
): string => {
  const currentDate = new Date().toLocaleDateString();
  const componentName =
    fileName?.replace(/\.(tsx?|jsx?)$/, '').replace(/[^a-zA-Z0-9]/g, '') || 'Component';
  const className = componentName.charAt(0).toUpperCase() + componentName.slice(1);


  const templates: Record<string, Record<string, string>> = {

    latex: {
      basic: `\\documentclass{article}\n% ${fileName} - LaTeX Article\n% Created: ${currentDate}\n% Compile with: pdflatex ${fileName}.tex\n\n% Packages (Unified Font Stack)\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{geometry}\n\\usepackage{graphicx}\n\\usepackage{amsmath, amssymb}\n\\usepackage{hyperref}\n\\geometry{a4paper, margin=2.5cm}\n\n% Metadata\n\\title{${className} Title}\n\\author{Author Name}\\date{\\today}\n\n\\begin{document}\n\\maketitle\n\n\\begin{abstract}\nA short abstract describing the content.\n\\end{abstract}\n\n\\section{Introduction}\nYour introduction text here. Cite references like \\\\cite{knuth1984tex}.\n\n\\section{Methods}\nExplain your methodology.\n\n\\section{Results}\nPresent results, tables, figures. See Figure~\\ref{fig:sample}.\n\n\\begin{figure}[h]\n  \\centering\n  % \\includegraphics[width=0.6\\textwidth]{figure.png}\n  \\caption{Sample figure caption}\n  \\label{fig:sample}\n\\end{figure}\n\n\\section{Conclusion}\nSummarize findings and future work.\n\n% References (if not using BibTeX)\n% \\begin{thebibliography}{9}\n% \\bibitem{knuth1984tex} Donald E. Knuth. The TeXbook. 1984.\n% \\end{thebibliography}\n\n\\end{document}`,
      article: `\\documentclass[11pt,a4paper]{article}\n% ${fileName} - Article Template\n% Created: ${currentDate}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{geometry}\n\\usepackage{amsmath, amssymb, amsthm}\n\\usepackage{graphicx}\n\\usepackage{hyperref}\n\\usepackage{csquotes}\n\\geometry{margin=2.5cm}\n\\title{${className} Article}\n\\author{Author Name}\\date{\\today}\n\\newtheorem{theorem}{Theorem}\n\\begin{document}\n\\maketitle\n\\begin{abstract}\nAbstract text here.\n\\end{abstract}\n\\section{Introduction}\nContent...\n\\section{Main Results}\n\\begin{theorem}\nStatement.\n\\end{theorem}\n\\section{Conclusion}\nSummary.\n\\bibliographystyle{plain}\n\\bibliography{references}\n\\end{document}`,
      report: `\\documentclass[12pt]{report}\n% ${fileName} - Report Template\n% Created: ${currentDate}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{geometry}\n\\usepackage{hyperref}\n\\usepackage{graphicx}\n\\geometry{margin=3cm}\n\\title{${className} Report}\n\\author{Author Name}\\date{\\today}\n\\begin{document}\n\\maketitle\n\\tableofcontents\n\\chapter{Introduction}\n...\n\\chapter{Background}\n...\n\\chapter{Methodology}\n...\n\\chapter{Results}\n...\n\\chapter{Conclusion}\n...\n\\appendix\n\\chapter{Appendix}\nExtra material.\n\\end{document}`,
      beamer: `\\documentclass{beamer}\n% ${fileName} - Beamer Presentation\n% Created: ${currentDate}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usetheme{Madrid}\n\\usecolortheme{default}\n\\title{${className} Presentation}\n\\author{Author Name}\n\\date{\\today}\n\\begin{document}\n\\begin{frame}\n  \\titlepage\n\\end{frame}\n\\begin{frame}{Outline}\n  \\tableofcontents\n\\end{frame}\n\\section{Introduction}\n\\begin{frame}{Introduction}\n  Key points here.\n\\end{frame}\n\\section{Content}\n\\begin{frame}{Main Idea}\n  Explanation here.\n\\end{frame}\n\\section{Conclusion}\n\\begin{frame}{Conclusion}\n  Summary and future work.\n\\end{frame}\n\\end{document}`,
      book: `\\documentclass{book}\n% ${fileName} - Book Template\n% Created: ${currentDate}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{hyperref}\n\\title{${className} Book}\n\\author{Author Name}\n\\date{\\today}\n\\begin{document}\n\\frontmatter\n\\maketitle\n\\tableofcontents\n\\mainmatter\n\\chapter{Introduction}\n...\n\\chapter{Second Chapter}\n...\n\\backmatter\n\\chapter{Appendix}\n...\n\\end{document}`,
    },
    bibtex: {
      basic: `@book{knuth1984tex,\n  author    = {Donald E. Knuth},\n  title     = {The TeXbook},\n  year      = {1984},\n  publisher = {Addison-Wesley},\n  address   = {Reading, Massachusetts}\n}\n\n@article{einstein1905,\n  author  = {Albert Einstein},\n  title   = {On the Electrodynamics of Moving Bodies},\n  journal = {Annalen der Physik},\n  year    = {1905}\n}`,
    },
    javascript: {
 vanilla: `// ${fileName} - Created ${currentDate}\n\n// Main functionality\nfunction main() {\n console.log(' JavaScript script loaded');\n \n // Your code here\n \n}\n\n// Execute\nmain();`,
      module: `// ${fileName} - ES6 Module\n// Created: ${currentDate}\n\nexport class ${className} {\n    constructor() {\n        this.initialize();\n    }\n    \n    initialize() {\n        console.log('Module initialized');\n    }\n}\n\nexport default ${className};`,
      node: `// ${fileName} - Node.js Script\n// Created: ${currentDate}\n\nconst path = require('path');\nconst fs = require('fs');\n\nclass ${className} {\n    constructor() {\n        this.start();\n    }\n    \n    start() {\n        console.log('Node.js application started');\n    }\n}\n\nconst app = new ${className}();\nmodule.exports = ${className};`,
      class: `// ${fileName} - ES6 Class\n// Created: ${currentDate}\n\nclass ${className} {\n    constructor(options = {}) {\n        this.options = options;\n        this.initialize();\n    }\n    \n    initialize() {\n        console.log('${className} initialized');\n    }\n    \n    // Add your methods here\n    \n}\n\nexport default ${className};`,
    },

    typescript: {
      basic: `// ${fileName} - TypeScript Module\n// Created: ${currentDate}\n\ninterface ${className}Options {\n    readonly name: string;\n    readonly version: string;\n}\n\nclass ${className} {\n    private options: ${className}Options;\n    \n    constructor(options: ${className}Options) {\n        this.options = options;\n        this.initialize();\n    }\n    \n    private initialize(): void {\n        console.log('TypeScript module initialized');\n    }\n}\n\nexport default ${className};\nexport type { ${className}Options };`,
  module: `// ${fileName} - TypeScript Module\n// Created: ${currentDate}\n\nexport interface I${className} {\n    id: string;\n    name: string;\n    createdAt: Date;\n}\n\nexport class ${className} implements I${className} {\n    public readonly id: string;\n    public name: string;\n    public readonly createdAt: Date;\n    \n    constructor(name: string) {\n        // SSR/legacy-safe UUID generation without external helpers\n        const __id = (typeof globalThis !== 'undefined' && (globalThis as any).crypto && typeof (globalThis as any).crypto.randomUUID === 'function')\n          ? (globalThis as any).crypto.randomUUID()\n          : (Date.now().toString() + '-' + Math.random().toString(36).slice(2));\n        this.id = __id;\n        this.name = name;\n        this.createdAt = new Date();\n    }\n}\n\nexport default ${className};`,
      class: `// ${fileName} - TypeScript Class\n// Created: ${currentDate}\n\nabstract class Base${className} {\n    protected abstract initialize(): void;\n}\n\nexport class ${className} extends Base${className} {\n    private _isInitialized = false;\n    \n    constructor() {\n        super();\n        this.initialize();\n    }\n    \n    protected initialize(): void {\n        this._isInitialized = true;\n        console.log('${className} initialized');\n    }\n    \n    public get isInitialized(): boolean {\n        return this._isInitialized;\n    }\n}\n\nexport default ${className};`,
      interface: `// ${fileName} - TypeScript Interface\n// Created: ${currentDate}\n\nexport interface I${className} {\n    readonly id: string;\n    name: string;\n    description?: string;\n    createdAt: Date;\n    updatedAt?: Date;\n}\n\nexport interface I${className}Service {\n    create(data: Omit<I${className}, 'id' | 'createdAt'>): Promise<I${className}>;\n    findById(id: string): Promise<I${className} | null>;\n    update(id: string, data: Partial<I${className}>): Promise<I${className}>;\n    delete(id: string): Promise<boolean>;\n}\n\nexport type ${className}CreateRequest = Omit<I${className}, 'id' | 'createdAt' | 'updatedAt'>;\nexport type ${className}UpdateRequest = Partial<${className}CreateRequest>;`,
    },

    react: {
      component: `// ${fileName} - React Component\n// Created: ${currentDate}\n\nimport React from 'react';\n\ninterface ${className}Props {\n    className?: string;\n    children?: React.ReactNode;\n}\n\nconst ${className}: React.FC<${className}Props> = ({ className, children }) => {\n    return (\n        <div className={className}>\n            <h1>${className}</h1>\n            {children}\n        </div>\n    );\n};\n\nexport default ${className};`,
      hook: `// ${fileName} - Custom React Hook\n// Created: ${currentDate}\n\nimport { useState, useEffect, useCallback } from 'react';\n\ninterface Use${className}Options {\n    initialValue?: any;\n}\n\ninterface Use${className}Return {\n    value: any;\n    setValue: (value: any) => void;\n    reset: () => void;\n    isLoading: boolean;\n}\n\nexport const use${className} = (options: Use${className}Options = {}): Use${className}Return => {\n    const [value, setValue] = useState(options.initialValue);\n    const [isLoading, setIsLoading] = useState(false);\n    \n    const reset = useCallback(() => {\n        setValue(options.initialValue);\n    }, [options.initialValue]);\n    \n    useEffect(() => {\n        // Effect logic here\n    }, []);\n    \n    return {\n        value,\n        setValue,\n        reset,\n        isLoading\n    };\n};\n\nexport default use${className};`,
      page: `// ${fileName} - React Page Component\n// Created: ${currentDate}\n\nimport React, { useEffect } from 'react';\nimport { Helmet } from 'react-helmet-async';\n\ninterface ${className}Props {\n    // Props here\n}\n\nconst ${className}: React.FC<${className}Props> = () => {\n    useEffect(() => {\n        // Page initialization\n    }, []);\n    \n    return (\n        <>\n            <Helmet>\n                <title>${className}</title>\n                <meta name=\"description\" content=\"${className} page\" />\n            </Helmet>\n            \n            <main className=\"container mx-auto px-4 py-8\">\n                <h1 className=\"text-3xl font-bold mb-6\">${className}</h1>\n                \n                {}\n                \n            </main>\n        </>\n    );\n};\n\nexport default ${className};`,
      context: `// ${fileName} - React Context\n// Created: ${currentDate}\n\nimport React, { createContext, useContext, useReducer, ReactNode } from 'react';\n\ninterface ${className}State {\n    // State properties\n}\n\ninterface ${className}Actions {\n    // Action types\n}\n\nconst initial${className}State: ${className}State = {\n    // Initial state\n};\n\nconst ${className}Context = createContext<{\n    state: ${className}State;\n    dispatch: React.Dispatch<${className}Actions>;\n} | null>(null);\n\nfunction ${className.toLowerCase()}Reducer(state: ${className}State, action: ${className}Actions): ${className}State {\n    switch (action.type) {\n        default:\n            return state;\n    }\n}\n\nexport const ${className}Provider: React.FC<{ children: ReactNode }> = ({ children }) => {\n    const [state, dispatch] = useReducer(${className.toLowerCase()}Reducer, initial${className}State);\n    \n    return (\n        <${className}Context.Provider value={{ state, dispatch }}>\n            {children}\n        </${className}Context.Provider>\n    );\n};\n\nexport const use${className} = () => {\n    const context = useContext(${className}Context);\n    if (!context) {\n        throw new Error('use${className} must be used within ${className}Provider');\n    }\n    return context;\n};\n\nexport default ${className}Provider;`,
    },

    python: {
      script: `#!/usr/bin/env python3\n# ${fileName} - Python Script\n# Created: ${currentDate}\n\nimport os\nimport sys\nfrom datetime import datetime\n\ndef main():\n    \"\"\"Main function\"\"\"\n    print(f\"Python script started: {datetime.now()}\")\n    \n    # Your code here\n    \n    print(\"Script completed successfully!\")\n\nif __name__ == \"__main__\":\n    main()`,
      class: `#!/usr/bin/env python3\n# ${fileName} - Python Class Module\n# Created: ${currentDate}\n\nfrom datetime import datetime\nfrom typing import Optional, Dict, Any\n\nclass ${className}:\n    \"\"\"${className} class for handling operations\"\"\"\n    \n    def __init__(self, name: str, **kwargs):\n        self.name = name\n        self.created_at = datetime.now()\n        self.config = kwargs\n        self._initialize()\n    \n    def _initialize(self) -> None:\n        \"\"\"Initialize the instance\"\"\"\n        print(f\"Initializing {self.__class__.__name__}: {self.name}\")\n    \n    def __str__(self) -> str:\n        return f\"{self.__class__.__name__}(name='{self.name}', created={self.created_at})\"\n    \n    def __repr__(self) -> str:\n        return self.__str__()\n\n# Example usage\nif __name__ == \"__main__\":\n    instance = ${className}(\"example\")\n    print(instance)`,
      flask: `#!/usr/bin/env python3\n# ${fileName} - Flask Application\n# Created: ${currentDate}\n\nfrom flask import Flask, request, jsonify\nfrom datetime import datetime\nimport os\n\napp = Flask(__name__)\napp.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev-key')\n\n@app.route('/')\ndef index():\n    return jsonify({\n        'message': 'Flask app is running!',\n        'timestamp': datetime.now().isoformat(),\n        'app': '${className}'\n    })\n\n@app.route('/api/health')\ndef health_check():\n    return jsonify({'status': 'healthy', 'service': '${className}'})\n\n@app.errorhandler(404)\ndef not_found(error):\n    return jsonify({'error': 'Not found'}), 404\n\nif __name__ == '__main__':\n    debug_mode = os.environ.get('FLASK_DEBUG', 'False').lower() == 'true'\n    port = int(os.environ.get('PORT', 5000))\n    app.run(debug=debug_mode, host='0.0.0.0', port=port)`,
      fastapi: `#!/usr/bin/env python3\n# ${fileName} - FastAPI Application\n# Created: ${currentDate}\n\nfrom fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\nfrom datetime import datetime\nfrom typing import List, Optional\nimport uvicorn\n\napp = FastAPI(\n    title=\"${className} API\",\n    description=\"FastAPI application generated by Enhanced IDE\",\n    version=\"1.0.0\"\n)\n\nclass ${className}Model(BaseModel):\n    id: Optional[int] = None\n    name: str\n    description: Optional[str] = None\n    created_at: Optional[datetime] = None\n\n@app.get(\"/\")\nasync def root():\n    return {\n        \"message\": \"${className} FastAPI is running!\",\n        \"timestamp\": datetime.now(),\n        \"docs\": \"/docs\"\n    }\n\n@app.get(\"/health\")\nasync def health_check():\n    return {\"status\": \"healthy\", \"service\": \"${className}\"}\n\nif __name__ == \"__main__\":\n    uvicorn.run(app, host=\"0.0.0.0\", port=8000, reload=True)`,
      django: `# ${fileName} - Django Application\n# Created: ${currentDate}\n\nfrom django.http import JsonResponse\nfrom django.views import View\nfrom django.views.decorators.csrf import csrf_exempt\nfrom django.utils.decorators import method_decorator\nfrom datetime import datetime\nimport json\n\n@method_decorator(csrf_exempt, name='dispatch')\nclass ${className}View(View):\n    \"\"\"${className} Django view\"\"\"\n    \n    def get(self, request):\n        return JsonResponse({\n            'message': 'Django view is working!',\n            'timestamp': datetime.now().isoformat(),\n            'view': '${className}View'\n        })\n    \n    def post(self, request):\n        try:\n            data = json.loads(request.body)\n            # Process data here\n            return JsonResponse({\n                'success': True,\n                'data': data,\n                'processed_at': datetime.now().isoformat()\n            })\n        except Exception as e:\n            return JsonResponse({\n                'success': False,\n                'error': str(e)\n            }, status=400)\n\n# URL patterns (add to urls.py)\n# path('${componentName.toLowerCase()}/', ${className}View.as_view(), name='${componentName.toLowerCase()}')`,
    },


    html: {
      basic: `<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>${componentName}</title>\n    <style>\n        body {\n            font-family: system-ui, -apple-system, sans-serif;\n            margin: 0;\n            padding: 2rem;\n            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n            min-height: 100vh;\n        }\n        .container {\n            max-width: 1200px;\n            margin: 0 auto;\n            background: white;\n            border-radius: 12px;\n            padding: 2rem;\n            box-shadow: var(--shadow-overlay);\n        }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <h1>Welcome to ${componentName}</h1>\n        <p>Created: ${currentDate}</p>\n        <!-- Your content here -->\n    </div>\n</body>\n</html>`,
    },

    css: {
      basic: `\n\n\n:root {\n    --primary-color: #667eea;\n    --secondary-color: #764ba2;\n    --text-color: #333;\n    --background-color: #fff;\n    --border-radius: 8px;\n    --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n}\n\n* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\nbody {\n    font-family: system-ui, -apple-system, sans-serif;\n    color: var(--text-color);\n    background: var(--background-color);\n    line-height: 1.6;\n}\n\n.container {\n    max-width: 1200px;\n    margin: 0 auto;\n    padding: 0 1rem;\n}\n\n`,
    },


    plain: {
      basic: `${fileName}\nCreated: ${currentDate}\n\n=== ${componentName} ===\n\nDescription:\nYour content goes here...\n\nNotes:\n- \n- \n- \n\n---\nGenerated by Enhanced IDE`,
    },
  };

  return (
    templates[languageId]?.[templateId] ||
    `// ${fileName}\n// Created: ${currentDate}\n\n// Your code here...`
  );
};
