import type {
  CompositeIndicatorDataset,
  CompositeIndicatorDefinition,
  CompositeIndicatorUnit,
} from "@/engine/simulation";

export interface CompositeIndicatorDemoDataset extends CompositeIndicatorDataset {
  bounds: [number, number, number, number];
  defaultScenarioName: string;
}

function rectanglePolygon(
  west: number,
  south: number,
  east: number,
  north: number,
): GeoJSON.Polygon {
  return {
    type: "Polygon",
    coordinates: [[
      [west, south],
      [east, south],
      [east, north],
      [west, north],
      [west, south],
    ]],
  };
}

const INDICATORS: CompositeIndicatorDefinition[] = [
  {
    id: "transit_access",
    label: "Transit accessibility",
    description: "Share of residents within 500 m of frequent transit.",
    unit: "%",
    source: "Mobility accessibility model",
    direction: "positive",
    referenceValue: 80,
    group: "Access",
  },
  {
    id: "green_space",
    label: "Green-space provision",
    description: "Public green-space area per resident.",
    unit: "m²/person",
    source: "Parks inventory",
    direction: "positive",
    referenceValue: 18,
    group: "Environment",
  },
  {
    id: "pm25",
    label: "PM2.5 concentration",
    description: "Annual mean PM2.5 concentration.",
    unit: "µg/m³",
    source: "Air-quality interpolated surface",
    direction: "negative",
    referenceValue: 12,
    group: "Environment",
  },
  {
    id: "housing_burden",
    label: "Housing cost burden",
    description: "Share of households spending more than 30% of income on housing.",
    unit: "%",
    source: "Household survey",
    direction: "negative",
    referenceValue: 30,
    group: "Equity",
  },
  {
    id: "health_access",
    label: "Primary-care access",
    description: "Residents within 15 minutes of primary-care services.",
    unit: "%",
    source: "Accessibility model",
    direction: "positive",
    referenceValue: 85,
    group: "Access",
  },
  {
    id: "flood_exposure",
    label: "Flood exposure",
    description: "Population share in the 100-year flood zone.",
    unit: "%",
    source: "Flood-risk overlay",
    direction: "negative",
    referenceValue: 8,
    group: "Risk",
  },
  {
    id: "employment_access",
    label: "Employment access",
    description: "Jobs reachable within 30 minutes by transit.",
    unit: "jobs",
    source: "Regional accessibility model",
    direction: "positive",
    referenceValue: 65000,
    group: "Opportunity",
  },
];

const UNITS: CompositeIndicatorUnit[] = [
  {
    id: "u1",
    label: "Harbor West",
    group: "south",
    geometry: rectanglePolygon(28.980, 41.000, 28.998, 41.018),
    values: {
      transit_access: 78,
      green_space: 11,
      pm25: 24,
      housing_burden: 43,
      health_access: 69,
      flood_exposure: 41,
      employment_access: 61200,
    },
    properties: { typology: "industrial edge", population: 18200 },
  },
  {
    id: "u2",
    label: "Civic Basin",
    group: "south",
    geometry: rectanglePolygon(28.998, 41.000, 29.016, 41.018),
    values: {
      transit_access: 91,
      green_space: 9,
      pm25: 27,
      housing_burden: 38,
      health_access: 82,
      flood_exposure: 22,
      employment_access: 76400,
    },
    properties: { typology: "civic core", population: 22600 },
  },
  {
    id: "u3",
    label: "South Terrace",
    group: "south",
    geometry: rectanglePolygon(29.016, 41.000, 29.034, 41.018),
    values: {
      transit_access: 66,
      green_space: 18,
      pm25: 20,
      housing_burden: 49,
      health_access: 61,
      flood_exposure: 33,
      employment_access: 48700,
    },
    properties: { typology: "mixed residential", population: 16700 },
  },
  {
    id: "u4",
    label: "Canal North",
    group: "central",
    geometry: rectanglePolygon(28.980, 41.018, 28.998, 41.036),
    values: {
      transit_access: 58,
      green_space: 22,
      pm25: 18,
      housing_burden: 41,
      health_access: 55,
      flood_exposure: 18,
      employment_access: 42100,
    },
    properties: { typology: "inland neighbourhood", population: 14100 },
  },
  {
    id: "u5",
    label: "Midtown Exchange",
    group: "central",
    geometry: rectanglePolygon(28.998, 41.018, 29.016, 41.036),
    values: {
      transit_access: 95,
      green_space: 13,
      pm25: 25,
      housing_burden: 36,
      health_access: 88,
      flood_exposure: 12,
      employment_access: 81200,
    },
    properties: { typology: "mixed-use core", population: 25100 },
  },
  {
    id: "u6",
    label: "Garden Crescent",
    group: "central",
    geometry: rectanglePolygon(29.016, 41.018, 29.034, 41.036),
    values: {
      transit_access: 74,
      green_space: null,
      pm25: 17,
      housing_burden: 31,
      health_access: 77,
      flood_exposure: 9,
      employment_access: 59300,
    },
    properties: { typology: "green residential", population: 19400 },
  },
  {
    id: "u7",
    label: "Ridge West",
    group: "north",
    geometry: rectanglePolygon(28.980, 41.036, 28.998, 41.054),
    values: {
      transit_access: 49,
      green_space: 27,
      pm25: 16,
      housing_burden: 28,
      health_access: 48,
      flood_exposure: 7,
      employment_access: 31800,
    },
    properties: { typology: "hillside low-rise", population: 11800 },
  },
  {
    id: "u8",
    label: "Station Heights",
    group: "north",
    geometry: rectanglePolygon(28.998, 41.036, 29.016, 41.054),
    values: {
      transit_access: 83,
      green_space: 16,
      pm25: null,
      housing_burden: 29,
      health_access: 71,
      flood_exposure: 6,
      employment_access: 55400,
    },
    properties: { typology: "transit suburb", population: 17100 },
  },
  {
    id: "u9",
    label: "University Hill",
    group: "north",
    geometry: rectanglePolygon(29.016, 41.036, 29.034, 41.054),
    values: {
      transit_access: 88,
      green_space: 21,
      pm25: 15,
      housing_burden: 34,
      health_access: 84,
      flood_exposure: 5,
      employment_access: 64300,
    },
    properties: { typology: "campus cluster", population: 20400 },
  },
  {
    id: "u10",
    label: "East Logistics",
    group: "east",
    geometry: rectanglePolygon(29.034, 41.000, 29.052, 41.018),
    values: {
      transit_access: 52,
      green_space: 8,
      pm25: 30,
      housing_burden: 46,
      health_access: 44,
      flood_exposure: 28,
      employment_access: 35800,
    },
    properties: { typology: "warehouse belt", population: 13600 },
  },
  {
    id: "u11",
    label: "East Garden",
    group: "east",
    geometry: rectanglePolygon(29.034, 41.018, 29.052, 41.036),
    values: {
      transit_access: 63,
      green_space: 24,
      pm25: 19,
      housing_burden: 32,
      health_access: null,
      flood_exposure: 11,
      employment_access: 46800,
    },
    properties: { typology: "residential extension", population: 15200 },
  },
  {
    id: "u12",
    label: "Innovation Ridge",
    group: "east",
    geometry: rectanglePolygon(29.034, 41.036, 29.052, 41.054),
    values: {
      transit_access: 79,
      green_space: 19,
      pm25: 14,
      housing_burden: 26,
      health_access: 79,
      flood_exposure: 4,
      employment_access: null,
    },
    properties: { typology: "knowledge district", population: 16100 },
  },
];

export function buildCompositeIndicatorDemoDataset(): CompositeIndicatorDemoDataset {
  return {
    id: "demo-composite-district",
    label: "Inner-District Composite Indicator Demo",
    indicators: INDICATORS,
    units: UNITS,
    bounds: [28.980, 41.000, 29.052, 41.054],
    defaultScenarioName: "Urban Wellbeing Composite",
  };
}
